### ISSUE TITLE
Can't Install the plugin offline through uploaded archive file

### ISSUE THREAD

**Issue by Astrocytosis** [jneilliii/OctoPrint-Playlist#11]
I'm running my octoprint offline and control it through an AP.
I was already able to install a couple of plugins by uploading the zip files directly onto octoprint.
But when I tried the same with your Plugin it always aborts the install because of no internet connection.

I've looked through the setup.py already but from my very crude understanding, I can't find the reason why a internet connection is even needed for the install.

Any help would be greatly appreciated!

**Comment by jneilliii** [comment]
An internet connection would only be required to install the plugin's dependencies (schedule) from the pypi wheel. The other plugins you installed probably did not require any additional python dependencies. 

https://pypi.org/project/schedule/
