### ISSUE TITLE
New designs won't add to the playlist unless I "print" them one time.

### ISSUE THREAD

**Issue by speedysk1** [jneilliii/OctoPrint-Playlist#18]
The button to add designs doesn't do anything unless I play the gcode once.  It doesn't even need to finish, but it has to be started.  I start it, cancel it, then I can add it to a play list.  You should be able to add files to the playlist without "printing" them one time first.

**Comment by jneilliii** [comment]
I think this is a bug already fixed in the latest release candidate. Please test that version.

**Comment by speedysk1** [comment]
Will do.  Thanks!

**Comment by speedysk1** [comment]
That worked with 1.15rc1.  Sandify drawings added no issue.
