### ISSUE TITLE
Clock/timer function enhancement

### ISSUE THREAD

**Issue by lockeandev** [jneilliii/OctoPrint-Playlist#4]
Can the timer function be expanded to include a "stop playback" time?  So you could run the machine from morning to bed every day?

At the end time you could issue an M226 or M600 to pause the printer till the restart time?

Great work!

**Comment by jneilliii** [comment]
That option is what is in settings right now.

**Comment by lockeandev** [comment]
Sorry, you're right. I did't see it in the settings but was only seeing the "play at" time setting on the playlist tab. I see the resume and pause function now.
