### ISSUE TITLE
"Play At" shows different times

### ISSUE THREAD

**Issue by AndiP1234** [jneilliii/OctoPrint-Playlist#5]
Hi,
the field "Play At" time shows 4 different times, flashing every second to another.
I can´t delete the times.

Best regards

**Comment by jneilliii** [comment]
Not sure I understand what you mean.

**Comment by simon-adriaanse** [comment]
I have the same problem. When adding a gcode file to the playlist and trying to set the “Play at time of day” setting, it changes the input to something random.

Then at a timely interval (i think every second or so) it keeps changing to random time values, 00:05 -> 00:06 -> 23:05 etc.

Greetings, Simon

**Comment by jneilliii** [comment]
What browser are you guys using?

**Comment by simon-adriaanse** [comment]
I’m using chrome. Latest version.

**Comment by jneilliii** [comment]
Ok, I'm unable to reproduce this on my end. What other plugins do you have installed? Is your OS anything other than English, specifically for time settings? If at all possible, detail the steps to reproduce so I know I'm pushing the buttons the same as you guys.

**Comment by AndiP1234** [comment]
**Server:**
Raspberry Pi 3+
Octoprint 1.4.0 (auto language)


**Client:**
Version 81.0.4044.122 (Offizieller Build) (64-Bit)
German
Win10 Pro 1909

I only installed this plugin.

If I reload the page while printing, the printer hangs several times. I think this is done by the plugin. After uninstalling, printing runs smoothly.

**Comment by jneilliii** [comment]
The hanging on reload of the page had been brought up in the community forum and wasn't specific to a plugin but resource consumption during page load. 

https://community.octoprint.org/t/th3dstudio-com-report-of-problem-with-octoprint/16573/10
