### ISSUE TITLE
update to 0.1.2 fails after many retries

### ISSUE THREAD

**Issue by karelv** [jneilliii/OctoPrint-Playlist#7]
![image](https://user-images.githubusercontent.com/787006/85324189-3964ae80-b47e-11ea-8369-d84eae2fb08c.png)

I click update & proceed:
![image](https://user-images.githubusercontent.com/787006/85324282-6749f300-b47e-11ea-8ce8-fac07068b99b.png)

![image](https://user-images.githubusercontent.com/787006/85324316-7761d280-b47e-11ea-84c1-87eb1ca0504b.png)

Got this error message.

Can you help?

**Comment by karelv** [comment]
I got this about a week ago, I retried several time. Also the url does not opens from my laptop...

**Comment by jneilliii** [comment]
Yeah, the update URL is wrong in the plugin since it was renamed. It was fixed in the latest version, so you need to reinstall manually using this URL in Plugin Manager to get things working again normally.

https://github.com/jneilliii/OctoPrint-Playlist/archive/master.zip
