### ISSUE TITLE
Feature Request - "queue up"/load the next file for printing

### ISSUE THREAD

**Issue by barrettj** [jneilliii/OctoPrint-Playlist#9]
Would it be possible to have the plugin just "queue up" the next file for printing, but not automatically start printing.

I believe in octoprint parlance this is just "loading" the file.

My use case is that I have some Flic buttons (Internet-of-Things button that you can program) that I have programmed to print the loaded file of the associated octoprint instance (doing a http post with command: start).  This means that after printing a file I can pop it off the build plate and then I just hit the button above the printer and it will print again.  I'm hoping with this plugin I'd be able to set a playlist of files (if possible even saving said playlist to load later/have multiple) and then after popping the items off the build plate I could just press my button and it'd be printing the next file (which was queue'd up/loaded after the previous file finished).

Thank you for your time/consideration.

**Comment by jneilliii** [comment]
Probably not going to develop much on this plugin since it monkey patches the comm layer and that's going to be changing drastically in a future release of octoprint. One thing that you might be able to do is use a pause command in the between files setting and then configure your button to send a resume api command instead of start?

**Comment by barrettj** [comment]
That should work - thanks!  There's two extra actions (double press and hold) that I don't have programmed so I can just make one of those be resume, so I can still have the "regular" functionality as well.
